---

- hosts: localhost
  connection: local
  sudo: yes
  vars:
    whoami: "{{ lookup('env', 'USER') }}"
    user_home: "{{ lookup('env', 'HOME') }}"
  roles:
    - basic
    - cc
    # - java
    # - clojure
    # - javascript
    - ruby
    - vcs
