---

- name: install subversion and mercurial
  apt: name={{item}} state=present
  with_items:
    - subversion
    - mercurial
    - cvs

- name: install git and some helper packages
  apt: name={{item}} state=present
  with_items:
    - git
    - git-svn
    - git-extras
    - tig

- name: git config user.name
  command: git config --global user.name "{{git_user_name}}"

- name: git config user.email
  command: git config --global user.email "{{git_user_email}}"
