---

# Seems Mac OS X(Yosemite) has git and svn installed already
- name: install subversion and mercurial
  homebrew: name={{item}} state=present
  with_items:
    - cvs
    - mercurial

- name: install some enhancements for git
  homebrew: name={{item}} state=present
  with_items:
    - git-extras
    - tig

- name: git config user.name
  command: git config --global user.name {{git_user_name}}

- name: git config user.email
  command: git config --global user.email {{git_user_email}}
