---

- name: install Oracle Java 8 via homebrew cask
  homebrew_cask: name=java state=present

- name: install maven and gradle
  homebrew: name={{item}} state=present
  with_items:
    - maven
    - gradle
