---

# You need to install xcode(https://developer.apple.com/xcode/) and then you get
# clang and nearly all the necessary libs/tools to build/install other apps.

- name: install C/C++ packages
  homebrew: name={{item}} state=present
  with_items:
    - cmake
