---

- name: install some small, awesome packages to boost your life
  apt: pkg={{item}} state=present
  with_items:
    - autoconf
    - aptitude
    - ack-grep
    - byobu
    - cloc
    - cscope
    - curl
    - htop
    - make
    - nmap
    - nmon
    - pinfo
    - proxychains
    - ranger
    - rlwrap
    - texinfo
    - tig

# (HACK): Some linux distributions didn't provide a default .bashrc.
- name: ensure $HOME/.bashrc is present
  command: touch {{user_home}}/.bashrc

- name: ensure $HOME/.zshrc is present
  command: touch {{user_home}}/.zshrc

# zsh and oh-my-zsh
- name: install zsh
  apt: pkg={{item}} state=present
  with_items:
    - zsh
    - zsh-lovers

- name: clone oh-my-zsh repo
  git: repo=https://github.com/robbyrussell/oh-my-zsh.git
       dest={{user_home}}/.oh-my-zsh

- name: backup original zshrc
  copy: src={{user_home}}/.zshrc dest={{user_home}}/.zshrc.orig

- name: deploy .zshrc
  template: src=files/zshrc.sh dest={{user_home}}/.zshrc owner={{whoami}}

- name: set zsh as default user shell
  user: name={{whoami}} shell=/usr/bin/zsh
