---

- name: install rbenv
  homebrew: name={{item}} state=present
  with_items:
    - rbenv
    - ruby-build

- name: init rbenv in bash
  lineinfile: dest={{user_home}}/.profile line="eval \"$(rbenv init -)\""

- name: init rbenv in zsh
  lineinfile: dest={{user_home}}/.zprofile line="eval \"$(rbenv init -)\""

- name: install some rbenv plugins
  homebrew: name={{item}} state=present
  with_items:
    - rbenv-gem-rehash
    - rbenv-default-gems

- name: copy gemrc
  copy: src=gemrc dest={{user_home}}/.gemrc

- name: update bash profile
  copy: src=default-gems dest={{user_home}}/.rbenv/default-gems
